[package]
name = "kasiopea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "nakup"
path = "src/A_nakup.rs"

[dependencies]
